name: CramerPDX
favicon: null
layout_spectrum: 1
typography_spectrum: 0.10233
title: 'Jason Cramer - Blogger, Jogger, & Husband'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfcfc'
    - '#7da1a9'
    - '#587881'
    - '#31484a'
    - '#ddd9d0'
  brandStrength: 0.6875
  lightness: 0.8125
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
